"""Validate the accumulator densities and the race against EMC2, an outside implementation.

`test_wald.py` and `test_lba.py` check these densities against *internal* references --
`scipy.stats.invgauss` for the Wald primitives, and `scipy.integrate.quad` self-consistency
for the LBA, which scipy has no closed form for. Neither pins the assembled race likelihood
to an independent implementation of the same models. EMC2 (Stevenson, Donzallaz, Heathcote
et al.) is that implementation, and this module compares against it.

This is the highest-value test in the package: an independent cross-implementation check, and
what pins `eamax`'s choice to floor the assembled trial total once (EMC2's
`log_likelihood_race` floors each trial at `min_ll = log(1e-10)` -- the same constant,
applied at the same place) rather than flooring each density component separately.

The comparison runs off CSV fixtures in `tests/reference/`, generated by the committed
`generate_emc2_reference.R`, so the suite needs no R and a future EMC2 change shows up as a
regeneration diff rather than a silent pass. That script's header documents the parameter
mapping; the short version is that EMC2's RDM takes `v, B, A, t0, s` with our threshold as
`B` and `A = 0` (we have no start-point variability), while its LBA takes decision time
`rt - t0`, threshold `b = A + B`, and our per-accumulator `s` as `sv`.

Two places where the implementations legitimately differ, both measured rather than assumed
and both bounded by the tolerances below:

1. EMC2's `pWald` carries about six digits, where `inv_gauss_logsf` reproduces
   `scipy.stats.invgauss.logsf` exactly. The RDM survival tolerance is therefore
   deliberately loose, and it is EMC2 that is the looser side.
2. The LBA density is a difference of nearly equal terms and underflows in float64 at small
   decision times, where EMC2's C++ kernel keeps going. `lba_logpdf` floors at `min_p`
   there, which is EMC2's own `min_ll`, so the two agree once that floor applies. The floor
   engages slightly early when `A` is well below 1 (the floored quantity is the density
   times `A`), which `FLOOR_BAND_NATS` bounds.
"""

import re
from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest

from eamax import race_loglik
from eamax.accumulators import LBA, Wald, inv_gauss_logpdf, inv_gauss_logsf
from eamax.accumulators.lba import lba_logpdf, lba_logsf

REFERENCE_DIR = Path(__file__).parent / "reference"

# EMC2's log_likelihood_race floors every trial at min_ll = log(1e-10); eamax.numerics uses
# the same 1e-10 as MIN_P. Comparing floored values is apples-to-apples, and floored values
# are what actually enter either package's likelihood.
MIN_LL = float(np.log(1e-10))

# How far above the floor EMC2's LBA density may still be on rows where ours has floored.
# The gap is `-log(A)`-ish, so it only opens up for A far below the prior's range
# (Gamma(6, 0.1), mean 0.6); the fixture's A = 0.05 edge rows are the ones that reach it.
FLOOR_BAND_NATS = 3.5

# The LBA density's relative precision decays smoothly as it falls towards the floor --
# measured across the fixture, agreement with EMC2 goes 3e-10 (10+ nats of headroom) ->
# 6e-9 (5 nats) -> 5e-8 (at the floor). Rows with less headroom than this take NEAR_FLOOR_TOL.
HEADROOM_NATS = 5.0
NEAR_FLOOR_TOL = 1e-6


def _read_fixture(name):
    return pd.read_csv(REFERENCE_DIR / name, comment="#")


def _read_header_params(name):
    """Pull the `# key=value` provenance lines off a dataset fixture."""
    params = {}
    with (REFERENCE_DIR / name).open() as handle:
        for line in handle:
            if not line.startswith("#"):
                break
            params.update({k: float(v) for k, v in re.findall(r"(\w+)=([-\d.eE+]+)", line)})
    return params


def _relerr(ref, res):
    # Absolute error once |ref| drops below 1, so log-densities near zero do not manufacture
    # a huge relative error.
    ref, res = np.asarray(ref), np.asarray(res)
    return np.abs(ref - res) / np.maximum(np.abs(ref), 1.0)


def _two_accumulator_race(accumulator, rt, response, t0, winner_params, loser_params):
    """Score a race whose per-accumulator parameters are given winner-first.

    The fixtures are laid out by role (`v_win` / `v_lose`) rather than by accumulator
    identity, so stacking winner-first and declaring every response to be accumulator 0 is
    the faithful translation.
    """
    params = {
        name: jnp.stack([jnp.asarray(winner_params[name]), jnp.asarray(loser_params[name])])
        for name in accumulator.param_names
    }
    return race_loglik(
        rt,
        jnp.zeros_like(jnp.asarray(rt), dtype=int),
        t0,
        lambda t: accumulator.log_pdf_sf(t, params),
    )


# ---------------------------------------------------------------------------
# RDM (Wald race)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def rdm_points():
    return _read_fixture("emc2_rdm_pointwise.csv")


def test_wald_logpdf_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        inv_gauss_logpdf(
            jnp.array((d.rt - d.t0).to_numpy()),
            (d.b / d.v_win).to_numpy(),
            ((d.b / d.s_win) ** 2).to_numpy(),
        ),
    )
    # EMC2 returns a density of exactly 0 (log -inf) once its own Wald underflows; those rows
    # carry no information about agreement, and the floored race test below covers them.
    finite = np.isfinite(d.log_pdf.to_numpy())
    assert finite.sum() > 250
    assert _relerr(d.log_pdf.to_numpy()[finite], ours[finite]).max() < 1e-9


def test_wald_logsf_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        inv_gauss_logsf(
            jnp.array((d.rt - d.t0).to_numpy()),
            (d.b / d.v_lose).to_numpy(),
            ((d.b / d.s_lose) ** 2).to_numpy(),
        ),
    )
    ref = d.log_sf.to_numpy()
    finite = np.isfinite(ref)
    sf = np.exp(ref)

    # Two tiers, because EMC2 evaluates the survival function as `1 - pWald(...)` in linear
    # space: the deeper the tail, the more of it is cancellation error. Ours matches scipy to
    # full double precision throughout, so these bounds describe EMC2's accuracy, not ours.
    bulk = finite & (sf >= 1e-4)
    tail = finite & (sf < 1e-4)
    assert _relerr(ref[bulk], ours[bulk]).max() < 1e-5
    assert _relerr(ref[tail], ours[tail]).max() < 1e-3


def test_wald_race_matches_emc2(rdm_points):
    d = rdm_points
    ours = np.array(
        _two_accumulator_race(
            Wald(),
            jnp.array(d.rt.to_numpy()),
            None,
            jnp.array(d.t0.to_numpy()),
            {"v": d.v_win.to_numpy(), "s": d.s_win.to_numpy(), "b": d.b.to_numpy()},
            {"v": d.v_lose.to_numpy(), "s": d.s_lose.to_numpy(), "b": d.b.to_numpy()},
        ),
    )
    ref = np.maximum(d.log_race.to_numpy(), MIN_LL)
    assert _relerr(ref, np.maximum(ours, MIN_LL)).max() < 1e-5


def test_wald_total_log_likelihood_matches_emc2():
    # Per-accumulator agreement cannot catch a swapped winner/loser role or a mis-assigned
    # s_true / s_false, because those are decided by the parameterization rather than by the
    # density functions. Scoring a whole dataset from (rt, choice) alone does.
    truth = _read_header_params("emc2_rdm_dataset.csv")
    d = _read_fixture("emc2_rdm_dataset.csv")

    rt = jnp.array(d.rt.to_numpy())
    response = jnp.array(d.choice.to_numpy(), dtype=int)
    ones = jnp.ones_like(rt)

    # Accumulator 0 is the "false" one, accumulator 1 the "true" one.
    params = {
        "v": jnp.stack([truth["v_intercept"] * ones, (truth["v_intercept"] + truth["v_slope"]) * ones]),
        "s": jnp.stack([truth["s_false"] * ones, truth["s_true"] * ones]),
        "b": jnp.stack([truth["b"] * ones, truth["b"] * ones]),
    }
    ours = float(
        jnp.sum(race_loglik(rt, response, truth["t0"], lambda t: Wald().log_pdf_sf(t, params))),
    )
    assert _relerr(truth["total_log_likelihood"], ours) < 1e-9


# ---------------------------------------------------------------------------
# LBA
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def lba_points():
    return _read_fixture("emc2_lba_pointwise.csv")


def _lba_pointwise_logpdf(d):
    return np.array(
        lba_logpdf(
            jnp.array((d.rt - d.t0).to_numpy()),
            d.v_win.to_numpy(),
            d.sv_win.to_numpy(),
            d.A.to_numpy(),
            (d.A + d.B).to_numpy(),
        ),
    )


def test_lba_logpdf_matches_emc2_where_representable(lba_points):
    d = lba_points
    ours = _lba_pointwise_logpdf(d)
    ref = d.log_pdf.to_numpy()
    above_floor = ~np.isclose(ours, MIN_LL)
    well_conditioned = above_floor & (ours - MIN_LL > HEADROOM_NATS)
    near_floor = above_floor & ~well_conditioned

    assert well_conditioned.sum() > 300
    assert _relerr(ref[well_conditioned], ours[well_conditioned]).max() < 1e-8
    assert _relerr(ref[near_floor], ours[near_floor]).max() < NEAR_FLOOR_TOL


def test_lba_logpdf_floor_is_bounded_against_emc2(lba_points):
    # The complement of the test above: wherever our density has floored, EMC2's value must be
    # at or near the floor too. This is the regression test for the floor being applied to the
    # *density* -- flooring the pre-normalization bracket instead returns
    # `-log(A) - log Phi(v/s)` nats *above* the floor, i.e. a tail overstated rather than
    # clamped, and at A = 0.6, b = 1.8, v = 3.5, s = 1.2, dt = 0.05 that is -22.51 against a
    # true value of e^-146.
    d = lba_points
    ours = _lba_pointwise_logpdf(d)
    floored = np.isclose(ours, MIN_LL)
    assert floored.any()
    assert np.all(ours[floored] == pytest.approx(MIN_LL))
    assert (d.log_pdf.to_numpy()[floored] - MIN_LL).max() < FLOOR_BAND_NATS


def test_lba_logsf_matches_emc2(lba_points):
    d = lba_points
    ours = np.array(
        lba_logsf(
            jnp.array((d.rt - d.t0).to_numpy()),
            d.v_lose.to_numpy(),
            d.sv_lose.to_numpy(),
            d.A.to_numpy(),
            (d.A + d.B).to_numpy(),
        ),
    )
    # No tiering needed here: unlike the Wald survival, the LBA's truncated-normal drift
    # leaves a heavy tail, so EMC2's `1 - plba(...)` stays well conditioned across the fixture.
    assert _relerr(d.log_sf.to_numpy(), ours).max() < 1e-8


def test_lba_race_matches_emc2(lba_points):
    d = lba_points
    b = (d.A + d.B).to_numpy()
    ours = np.array(
        _two_accumulator_race(
            LBA(),
            jnp.array(d.rt.to_numpy()),
            None,
            jnp.array(d.t0.to_numpy()),
            {"v": d.v_win.to_numpy(), "s": d.sv_win.to_numpy(), "A": d.A.to_numpy(), "b": b},
            {"v": d.v_lose.to_numpy(), "s": d.sv_lose.to_numpy(), "A": d.A.to_numpy(), "b": b},
        ),
    )
    ref = np.maximum(d.log_race.to_numpy(), MIN_LL)
    floored = np.isclose(ours, MIN_LL)
    well_conditioned = ~floored & (ours - MIN_LL > HEADROOM_NATS)
    near_floor = ~floored & ~well_conditioned

    assert _relerr(ref[well_conditioned], ours[well_conditioned]).max() < 1e-8
    assert _relerr(ref[near_floor], ours[near_floor]).max() < NEAR_FLOOR_TOL
    # Same band as the pointwise density: where we floor, EMC2 must be near the floor too.
    assert (ref[floored] - MIN_LL).max() < FLOOR_BAND_NATS


def test_lba_total_log_likelihood_matches_emc2():
    truth = _read_header_params("emc2_lba_dataset.csv")
    d = _read_fixture("emc2_lba_dataset.csv")

    rt = jnp.array(d.rt.to_numpy())
    response = jnp.array(d.choice.to_numpy(), dtype=int)
    ones = jnp.ones_like(rt)
    b = truth["A"] + truth["B"]

    params = {
        "v": jnp.stack([truth["v_intercept"] * ones, (truth["v_intercept"] + truth["v_slope"]) * ones]),
        "s": jnp.stack([truth["s_false"] * ones, truth["s_true"] * ones]),
        "A": jnp.stack([truth["A"] * ones, truth["A"] * ones]),
        "b": jnp.stack([b * ones, b * ones]),
    }
    ours = float(
        jnp.sum(race_loglik(rt, response, truth["t0"], lambda t: LBA().log_pdf_sf(t, params))),
    )
    assert _relerr(truth["total_log_likelihood"], ours) < 1e-9
